![irl](https://www.jobvacancyresult.com/storage/company/1976_innomatics.png)

# Nummpy Problem

## Name: Mohammad Wasiq

## E-mail: `mohammadwasiq0786@gmail.com`

# Numpy - Problem Solving

In [1]:
import numpy as np

arr_1= np.array([[1, 2, 3], [4, 5, 6]])

arr_1.shape

(2, 3)

In [2]:
arr_2= np.array([0, 1, 0])
arr_2.shape

(3,)

In [3]:
arr_1 + arr_2

array([[1, 3, 3],
       [4, 6, 6]])

In [4]:
arr_1= np.array([[1, 2, 3], [4, 5, 6]])

arr_2= np.array([[1], [2], [0]])

arr_1 + arr_2

ValueError: ignored

## Broadcasting
**Rules:** Start matching the dimensions backward (Right to Left)
* Compatible - If same number appears or if one of them is 1.
* Incompatible - Otherwise

In [5]:
arr_1= np.array([[1, 2, 3], [4, 5, 6]])

arr_2= np.array([1, 2, 3])

arr_1 + arr_2

array([[2, 4, 6],
       [5, 7, 9]])

In [6]:
arr_1= np.array([[1, 2, 3], [4, 5, 6]])

arr_2= np.array([[1], [2]])

arr_1 + arr_2

array([[2, 3, 4],
       [6, 7, 8]])

In [7]:
arr_1= np.array([[1, 2, 3, 4, 5]])

arr_2= np.array([1, 2, 3, 4])

arr_1 + arr_2

ValueError: ignored

In [8]:
arr_1= np.array([[1], [2], [3], [4], [5]])

arr_2= np.array([1, 2, 3, 4])

arr_1 + arr_2

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

### Question:
**Randomly generate a matrix of shape (1Million, 2) and perform below mentioned operations:**

a. Find the distance between each 2 - 
<br> Dimensional data point from the centroid (i.e. mean) of the given dataset.
<br> Append the newly calculated distances as new colummn with the given dataset.

b. Given any data point, generate 3 closest neighbors from it.

**Solution:**
* Step 1: Generate the Matrix
* Step 2: Compute Centroid
* Step 3: Compute Distance

In [9]:
# Step 1: Generate the Matrix
import numpy as np

arr= np.random.rand(1000000, 2)

arr.shape

(1000000, 2)

In [10]:
# Step 2: Compute Centroid
centroid= np.mean(arr)

centroid.shape

()

In [11]:
centroid

0.5001681866338552

In [12]:
# Step 2: Compute Centroid
centroid= np.mean(arr, axis= 0)

print(centroid.shape)
print(centroid)

(2,)
[0.50063211 0.49970427]


$$d= \sqrt{(side1)^2 + (side2)^2}$$

In [13]:
# Step 3: Compute Distance b/w each 2D datapoint and the centroid
dist= np.sqrt(np.sum((arr - centroid)**2, axis= 1))
dist.shape

(1000000,)

In [14]:
dist

array([0.39316399, 0.57895451, 0.16314614, ..., 0.38705741, 0.47908046,
       0.45267848])

### Question:
**Randomly generate a matrix of shape (1Million, 3) and perform below mentioned operations:**

a. Find the distance between each 2 - 
<br> Dimensional data point from the centroid (i.e. mean) of the given dataset.
<br> Append the newly calculated distances as new colummn with the given dataset.

b. Given any data point, generate 3 closest neighbors from it.

**Solution:**
* Step 1: Generate the Matrix
* Step 2: Compute Centroid
* Step 3: Compute Distance

In [15]:
dist.reshape(-1, 1).shape

(1000000, 1)

In [16]:
new_arr= np.hstack([arr, dist.reshape(-1, 1)])

new_arr.shape

(1000000, 3)

In [17]:
new_arr[dist.argsort()][:3]

array([[5.00641324e-01, 4.99588238e-01, 1.16394206e-04],
       [5.00406617e-01, 4.99724201e-01, 2.26368438e-04],
       [5.00012139e-01, 4.99695432e-01, 6.20029824e-04]])